namespace EventSimulator.Events
{
    using System;

    /// <summary>
    /// Represents a click event generated by a user.
    /// A click event tells the entry, exit time of a page,
    /// as well as the page the user is on what page the user is going to.
    /// </summary>
    public class ClickEvent : Event
    {
        /// <summary>
        /// The url of the page on which the event is generated.
        /// Does not include the domain.
        /// </summary>
        public string CurrentUrl { get; set; }

        /// <summary>
        /// The url of the page that is being navigated to when the event
        /// is generated.
        /// </summary>
        public string NextUrl { get; set; }

        /// <summary>
        /// The time the user logged on to the page.
        /// </summary>
        public DateTime EntryTime { get; set; }

        /// <summary>
        /// The time the user clicks on the link to generate the event.
        /// </summary>
        public DateTime ExitTime { get; set; }

        #region Constructors

        public ClickEvent()
        { }

        /// <summary>
        /// Makes a shallow copy of e.
        /// </summary>
        /// <param name="e">The event to be copied.</param>
        public ClickEvent(ClickEvent e) : base(e)
        {
            CurrentUrl = e.CurrentUrl;
            NextUrl = e.NextUrl;
            EntryTime = e.EntryTime;
            ExitTime = e.ExitTime;
        }

        /// <summary>
        /// Makes a shallow copy, but only copies inherited members.
        /// </summary>
        /// <param name="e"> The event to be copied.</param>
        public ClickEvent(Event e) : base(e)
        {
            // Nothing to do here.
        }



        #endregion
    }
}
